spring.application.name=HibernateDemo
# MySQL Database

spring.datasource.url=jdbc:mysql://localhost:3306/hibernatedemo
spring.datasource.username=root
spring.datasource.password=Tanay@2447095

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
