spring.application.name=JPARelationshipDemo
spring.datasource.url=jdbc:mysql://localhost:3306/relationship_demo
spring.datasource.username=root
spring.datasource.password=Tanay@2447095

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true